/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoroCollectiveRouteImport } from './routes/coro-collective'
import { Route as FabricationRouteImport } from './routes/fabrication'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as JournalSlugRouteImport } from './routes/journal/$slug'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoroCollectiveRoute = CoroCollectiveRouteImport.update({
  id: '/coro-collective',
  path: '/coro-collective',
  getParentRoute: () => rootRouteImport,
} as any)
const FabricationRoute = FabricationRouteImport.update({
  id: '/fabrication',
  path: '/fabrication',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/contact': typeof ContactRoute
  '/coro-collective': typeof CoroCollectiveRoute
  '/fabrication': typeof FabricationRoute
  '/journal': typeof JournalRouteWithChildren
  '/materials': typeof MaterialsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/contact': typeof ContactRoute
  '/coro-collective': typeof CoroCollectiveRoute
  '/fabrication': typeof FabricationRoute
  '/journal': typeof JournalRouteWithChildren
  '/materials': typeof MaterialsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/applications': typeof ApplicationsRoute
  '/contact': typeof ContactRoute
  '/coro-collective': typeof CoroCollectiveRoute
  '/fabrication': typeof FabricationRoute
  '/journal': typeof JournalRouteWithChildren
  '/materials': typeof MaterialsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/applications'
    | '/contact'
    | '/coro-collective'
    | '/fabrication'
    | '/journal'
    | '/materials'
    | '/projects'
    | '/resources'
    | '/journal/$slug'
    | '/projects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/applications'
    | '/contact'
    | '/coro-collective'
    | '/fabrication'
    | '/journal'
    | '/materials'
    | '/projects'
    | '/resources'
    | '/journal/$slug'
    | '/projects/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/applications'
    | '/contact'
    | '/coro-collective'
    | '/fabrication'
    | '/journal'
    | '/materials'
    | '/projects'
    | '/resources'
    | '/journal/$slug'
    | '/projects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApplicationsRoute: typeof ApplicationsRoute
  ContactRoute: typeof ContactRoute
  CoroCollectiveRoute: typeof CoroCollectiveRoute
  FabricationRoute: typeof FabricationRoute
  JournalRoute: typeof JournalRouteWithChildren
  MaterialsRoute: typeof MaterialsRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ResourcesRoute: typeof ResourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coro-collective': {
      id: '/coro-collective'
      path: '/coro-collective'
      fullPath: '/coro-collective'
      preLoaderRoute: typeof CoroCollectiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fabrication': {
      id: '/fabrication'
      path: '/fabrication'
      fullPath: '/fabrication'
      preLoaderRoute: typeof FabricationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApplicationsRoute: ApplicationsRoute,
  ContactRoute: ContactRoute,
  CoroCollectiveRoute: CoroCollectiveRoute,
  FabricationRoute: FabricationRoute,
  JournalRoute: JournalRouteWithChildren,
  MaterialsRoute: MaterialsRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ResourcesRoute: ResourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
